### ISSUE TITLE
Hook up email client to reports@cyber.dhs.gov

### ISSUE THREAD

**Issue by itsmostafa** [cisagov/con-pca-web#10]
# 🚀 Feature Proposal

Send subscription status reports and sample emails to be used for phishing from the proposed email address: reports@cyber.dhs.gov

## Motivation
Con-PCA client side emails should be sent from an official DHS url to Con-PCA customers

## Pitch
Con-PCA client side emails should be sent from an official DHS email address.

**Comment by jsf9k** [comment]
You need to be able to send emails from `reports@cyber.dhs.gov`.  That SES domain is configured in the COOL DNS account. 
 That means your EC2 instance where your Docker container is running needs to be able to assume a role in the COOL DNS account that has permissions to send emails via AWS SES.  We currently do something very similar, where we send emails from Docker containers running in EC2 instances located in our old CyHy AWS account, which has not yet been moved over to the COOL.  I will walk you through how that works.

1. [Here](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/develop/sessendemail_role.tf) is the Terraform code that defines the role you would be assuming in the COOL DNS account, and [here](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/develop/sessendemail_policy.tf) is the corresponding TF code for the policy.  We would need to insert your account ID or IDs [here](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/develop/sessendemail_role.tf#L15-L18) and re-apply the Terraform.  Then your AWS _account_ (but not yet your EC2 instance) will have permission to assume that role, whose ARN we can give you.
1. The second piece is configuring your EC2 instance to be able to assume the role.  You can see [here](https://github.com/cisagov/cyhy_amis/blob/develop/terraform/bod_docker_ec2.tf) how we create an instance role for our EC2 instance running in the CyHy account.  In particular, [here](https://github.com/cisagov/cyhy_amis/blob/develop/terraform/bod_docker_ec2.tf#L92-L107) is the policy attached to that role that allows assumption of the role I talked about in the previous paragraph.  The ARN we would give you is precisely what is stored in the variable `var.ses_role_arn`.
1. The last piece is actually assuming the role inside your Docker container.  There are a few ways to do this.  What we have done is [create an AWS configuration as part of the Ansible role that installs the Docker composition in which your Docker container runs](https://github.com/cisagov/cyhy_amis/blob/develop/ansible/roles/cyhy_mailer/tasks/main.yml#L32-L42).  The Docker composition then [treats that AWS configuration as a Docker secret](https://github.com/cisagov/cyhy-mailer/blob/develop/docker-compose.yml#L7-L8) and [makes it available to the Docker container](https://github.com/cisagov/cyhy-mailer/blob/develop/docker-compose.yml#L13-L20).  Now, when the `cyhy-mailer` application runs inside the Docker container, it can just use [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) to [send the email](https://github.com/cisagov/cyhy-mailer/blob/develop/cyhy/mailer/cli.py#L286-L328).

N.B.:  If your container needs to assume more than one role to perform its function then you have to create an AWS configuration with multiple profiles and tell boto3 to use one for sending email, another for accessing S3, etc.  Look [here](https://github.com/cisagov/cyhy_amis/blob/develop/ansible/roles/orchestrator/tasks/main.yml#L53-L66) for an example of that.

**Comment by jsf9k** [comment]
@mostafac0des - I am going to go ahead and close this issue, but please reopen it if you have more questions or feel I didn't address the issue you brought up.

**Comment by jsf9k** [comment]
INL AWS account(s) were given permission to assume the email-sending role in cisagov/cool-dns-cyber.dhs.gov#18.
